from pathlib import Path
import hashlib,json,shutil,subprocess,re
import imageio_ffmpeg
root=Path(__file__).resolve().parents[1]; ff=imageio_ffmpeg.get_ffmpeg_exe()
titles=['First Light Frontier','Rustwind Traverse','Toxic Glasslands','Obsidian Tempest','Eventide Abyss']
urls=['zuL9JSrto8HQNY16Jvm5?selectedSongId=mvDSGT8pzNHKftZ9fisT','j3nzFPkQgs60kehqkgA4?selectedSongId=lJp2ofSCErqHw5JBvJEr','0EK0iauhaxybPzbEUck9?selectedSongId=JwuGj4en93ubevC5TiSu','EbOUxYc9cboLBKrPcFkG?selectedSongId=XxV62Wl6iaNhLmmq0YM3','QEEmuhF30vDTgHzo9pmA?selectedSongId=lHVUDRoiJMuqrrEP31u8']
prompts=[
'Original instrumental game exploration soundtrack, title First Light Frontier. Tier 1 welcoming alien planet, warm felt piano, soft analog pads, delicate marimba and sparse organic percussion, 72 BPM. Quiet curiosity and hopeful small beginnings with wide open space. Two minutes, gentle evolving background for mining and building, restrained dynamics, no vocals or choir, no sound effects, no big climax, soft loop-friendly opening and ending.',
'Original instrumental science fiction exploration soundtrack, title Rustwind Traverse. Tier 2 rugged alien planet, dusty plucked strings, muted hand drums, dry shakers and subdued analog bass pulse, 84 BPM. Curious but wary, rocky wilderness and arduous expedition, occasional minor harmonies. Two minutes of evolving game background, no voices or choir, no sound effects, restrained dynamics, soft loop-friendly opening and ending.',
'Original instrumental science fiction exploration soundtrack, title Toxic Glasslands. Tier 3 hostile alien planet, cold glass mallets, asymmetrical electronic pulses, deep synth bass and bowed metallic textures, 94 BPM. Uneasy discovery and environmental danger, mysterious industrial alien landscape, moderate tension with breathing room for gameplay. Two minutes, no vocals or choir, no sound effects, no jump scares, restrained dynamics, soft loop-friendly opening and ending.',
'Original instrumental science fiction exploration soundtrack, title Obsidian Tempest. Tier 4 brutal alien planet, low bowed strings, granular synthesizer drones, heavy muted toms and restless syncopated ostinato, 106 BPM. Storm ravaged volcanic wilderness, oppressive isolation and determined survival. Two minutes of sustained exploratory tension, no vocals or choir, no sound effects, no cinematic impacts or sudden climax, controlled loudness, soft loop-friendly edges.',
'Original instrumental science fiction exploration soundtrack, title Eventide Abyss. Tier 5 extreme alien planet, abyssal sub bass, dissonant low strings, distorted but soft analog pulses and irregular measured industrial percussion, 116 BPM. Vast merciless landscape, existential dread and resilient forward motion, highest tension but still background exploration music. Two minutes, no vocals or choir, no sound effects, no jump scares or piercing highs, controlled loudness, soft loop-friendly opening and ending.']
records=[]
for tier,title in enumerate(titles,1):
 downloaded=max((Path.home()/'Downloads').glob(title.replace(' ','_')+'*.mp3'),key=lambda p:p.stat().st_mtime)
 id=f'music_planet_t{tier}_v1';source=root/f'audio/source/elevenlabs/{id}.mp3';out=root/f'우주-비즈니스/assets/audio/{id}.mp3';shutil.copy2(downloaded,source)
 measured=subprocess.run([ff,'-hide_banner','-i',str(source),'-af','loudnorm=I=-20:TP=-3:LRA=11:print_format=json','-f','null','-'],capture_output=True,text=True,check=True).stderr
 stats=json.JSONDecoder().raw_decode(measured[measured.rfind('{'):])[0]; filt='loudnorm=I=-20:TP=-3:LRA=11:'+':'.join(k+'='+stats[v] for k,v in [('measured_I','input_i'),('measured_TP','input_tp'),('measured_LRA','input_lra'),('measured_thresh','input_thresh'),('offset','target_offset')])+':linear=true'
 subprocess.run([ff,'-y','-v','error','-i',str(source),'-af',filt,'-ar','44100','-ac','2','-b:a','192k',str(out)],check=True)
 records.append({'id':id,'tier':tier,'title':title,'prompt':prompts[tier-1],'provider':'ElevenLabs Music v2 web','url':'https://elevenlabs.io/app/music/project/'+urls[tier-1],'instrumental':True,'duration_setting_seconds':120,'variations':1,'displayed_credits':1800,'download_name':downloaded.name,'source':str(source.relative_to(root)),'game_file':str(out.relative_to(root)),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'game_sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'processing':'Two-pass loudnorm -20 LUFS / -3 dBTP ceiling; stereo 44.1kHz 192kbps MP3. Runtime loop edge fade 0.45s, place crossfade 2.5s.','source_loudness':stats,'status':'generated_integrated_pending_game_review'})
 print(id,'imported',flush=True)
(root/'audio/manifests/planet-tier-music.json').write_text(json.dumps({'date':'2026-09-09','jobs':records,'generation_note':'T2 duplicate generation occurred during native UI update; latest T2 selected. Six generations total, displayed 1800 credits each. No subscription change.'},ensure_ascii=False,indent=2)+'\n')
