extends SceneTree
const MapBake=preload("res://scripts/ui/planet_map_bake.gd")
const Actor=preload("res://scripts/actors/creatures/bestiary_actor.gd")
var failures:=0
var probes:=0
func _initialize() -> void:run.call_deferred()
func check(ok: bool,label: String) -> void:
 print("PASS " if ok else "FAIL ",label)
 if not ok:failures+=1
func probe(at: Vector3,_reach: float) -> Dictionary:
 probes+=1
 return {"point":Vector3(at.x,0,at.z),"normal":Vector3.UP}
func run() -> void:
 var field:=FrontierTerrainField.new();field.configure(71503)
 var planet: Dictionary={"kind":"glacial","traits":{"water":50,"temperature":12}}
 var job:=MapBake.new();job.configure(field,planet,Vector2(-200,-150),Vector2(500,320),"first")
 var task:=WorkerThreadPool.add_task(job.run)
 while not WorkerThreadPool.is_task_completed(task):await process_frame
 WorkerThreadPool.wait_for_task_completion(task)
 check(job.result.get_size()==Vector2i(160,100),"map retains full raster resolution")
 check(field.height_samples.is_empty() and not is_same(field,job.field),"map worker never touches live terrain or its caches")
 # Golden raster generated by the pre-change synchronous implementation (Godot 4.7.2).
 check(job.result.get_data().hex_encode().sha256_text()=="a2c3b1cb1366d3c420d1e12f9baf9701681d18aa27ce8830a84477b27a3ae9a9","threaded map matches original pixels exactly")
 var ui:=FrontierPlanetMap.new();root.add_child(ui);ui.set_process(false)
 ui.canvas=Control.new();ui.add_child(ui.canvas);ui.canvas.size=Vector2(500,320)
 ui.terrain=field;ui.body=planet;ui.cached_id="one";ui.meters_per_pixel=1
 ui.bake_job=MapBake.new();ui.bake_job.configure(field,planet,Vector2.ZERO,ui.canvas.size,ui._bake_key())
 ui.bake_task=WorkerThreadPool.add_task(ui.bake_job.run)
 ui.focus=Vector2(128,0)
 while ui.bake_task>=0:
  ui._finish_bake();await process_frame
 check(ui.texture==null,"stale map result rejected after pan")
 ui.bake_job=MapBake.new();ui.bake_job.configure(field,planet,Vector2.ZERO,ui.canvas.size,ui._bake_key())
 ui.bake_task=WorkerThreadPool.add_task(ui.bake_job.run)
 ui.free()
 check(true,"closing map drains its worker")
 var stage:=Node3D.new();root.add_child(stage)
 var camera:=Camera3D.new();stage.add_child(camera);camera.current=true
 var actor:=Actor.new();stage.add_child(actor);actor.configure(FrontierEcologyCatalog.form("bio_grazer_01"));actor.set_process(false)
 actor.enable_field_culling()
 actor.drive_ground(Vector3(100,0,0),Basis.IDENTITY,.016,probe,false,1)
 check(probes==0 and actor.global_position.x==100,"hidden distant contact probes sleep while authoritative root moves")
 actor.drive_ground(Vector3.ZERO,Basis.IDENTITY,.016,probe,false,1)
 check(probes>0 and not actor.ground_motion.contacts_suspended,"audible nearby feet resume immediately")
 var initial:=probes
 for i in 100:actor.drive_ground(Vector3.ZERO,Basis.IDENTITY,.016,probe,false,1)
 check(probes==initial,"unchanged planted terrain does not require periodic probes")
 actor.drive_ground(Vector3.ZERO,Basis.IDENTITY,.016,probe,false,2)
 check(probes>initial,"terrain revision refreshes planted contacts")
 for c in actor.ground_motion.contacts:check(c.ready and c.position.is_finite(),"resumed feet have finite contacts")
 stage.free()
 print("PRESENTATION_BUDGET failures ",failures);quit(1 if failures else 0)
